### ISSUE TITLE
How to work with Flask blueprint?

### ISSUE THREAD

**Issue by ivymichael** [mrf345/flask_datepicker#2]
Hi,

I have several blueprints with my flask app, how can flask-datepicker work with them?
I try to import the datepicker in blueprint registeration python file, which comes like

```
app = Flask(__name__)
datepicker(app, local=['static/js/jquery-ui.js', 'static/css/jquery-ui.css'])
```

then just directly hover to html file, and use 

```
<script type="text/javascript">
  {{ super() }}
  {{ datepicker.loader() }} {# to load jQuery-ui #}
  {{ datepicker.picker(id=".dp") }}
</script>
```
then I got 

```

File "/var/www/FlaskApp/FlaskApp/venv/lib/python3.6/site-packages/Flask_Datepicker-0.1-py3.6.egg/flask_datepicker/__init__.py", line 72, in loader
[Wed Mar 21 16:01:15.957248 2018] [wsgi:error] [pid 32619:tid 139871219263232] [remote 149.197.123.138:55516]     "datepicker.loader() file not found "))
[Wed Mar 21 16:01:15.957255 2018] [wsgi:error] [pid 32619:tid 139871219263232] [remote 149.197.123.138:55516] FileNotFoundError: datepicker.loader() file not found 
```

Are I miss-understanding something?

**Comment by mrf345** [comment]
Hello,
It should work flawlessly with blueprints, with one exception if a different static folder is assigned to the blueprints. I've not tried that yet TBH. However the most probable cause is wrong path, since `os.path.isfile()` raised an error. maybe you're using Windows OS, in that case you'll have to use `\\` instead of `/` :
```javascript
datepicker(app, local=['static\\js\\jquery-ui.js', 'static\\css\\jquery-ui.css'])
```

Another thing, there's no need to use `<script></script>`, use `{% block scripts %}` if you're using flask-bootstrap or you've defined your own block scripts, otherwise just use:
```javascript
  {{ datepicker.loader() }}
  {{ datepicker.picker(id=".dp") }}
```

**Comment by mrf345** [comment]
Well i went back to the code, replace `'/'` with `'\\'` will escape the raised error. but the browser won't recognize the path :). I'm working on an update

**Comment by mrf345** [comment]
just updated it, 0.3 release should have this issue's fixed whether `'/'` or `'\\'` is used.

**Comment by mrf345** [comment]
@ivymichael Can you conform, that the issue's resolved ?

**Comment by ivymichael** [comment]
Hi,

So sorry for the late reply, I was travelling for past two days.
I tried, still the same error.
Actually, I am using Ubuntu on my server, and the I have only one static folder through whole app and didn`t use Flask-Bootstrap.
the structure:
```
/www
.../FlaskApp
   .../FlaskApp
      .../venv
      .../__init__.py       -( File A )
      .../Blueprint1
         ..../templates   -(this blueprint related html files.)
         ..../routes.py     -( File B )
         ..../__init__.py    -( File C )
      .../Blueprint2
      .../static
      .../templates     - (app base layout templates, like headers.html, layout.html)
```

In routes.py file B, I initialize blueprint like this:

```
from flask import Blueprint
mod = Blueprint('Blueprint1', __name__, template_folder='templates')

@mod.route('/test')
def ..
..
```

then in init file A, I register the blueprint, like this:
```
from flask import Flask
..
app = Flask(__name__)
datepicker(app, local=['static/js/jquery-ui.js', 'static/css/jquery-ui.css'])
..
from FlaskApp.Blueprint1.routes import mod
..
..
app.register_blueprint(Blueprint1.routes.mod, url_prefix='/blueprint1')
```
In init file C, there is nothing inside.

I guess:
1. maybe I should move datepicker(app...) to file B as datepicker(mod...), not file A?
2. I didn`t pass any datepicker in my view function, shall I pass any? like render_template('/test', datepicker = datepicker)?

Sorry, somehow I am quite confused, why I can use {{datepicker.loader()}} without passing it?

**Comment by mrf345** [comment]
No apologies necessary,  I'm happy to help,
I think there's a big confusion :) `local=[]` is an optional argument, you should use if you want to load your own jquery-ui source code from the static folder, otherwise it shouldn't be used and the extension will be loaded from remote CDN. 

`datapicker(app, local=[])` is the module which loads the extension and extends the Flask app instance.
Why not `datapicker.loader()` because loader is just a function inside `datapicker(app, local=[])` so it inherits its settings, Hopefully i didn't confuse you even more :)

`datapicker()` was loaded correctly according to the log you shared, so the problem certainly is with jquery-ui local files. try to use it without them by `datepicker(app)` instead of `datepicker(app, local=[...])` 
or make sure that they actually exist in the correct paths `static/css/jquery-ui.css`  and `static/js/jquery-ui.js`

An other thing if you're not using flask-bootstrap, make sure that you have jquery loaded in your webpage, since jquery-ui depends on it.

**Comment by ivymichael** [comment]
Thank you very much,
It is ok to close this issue now.
